import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.barakah.services',
  appName: 'Barakah',
  webDir: 'dist',
  // Custom URL scheme used by the native OAuth deep link callback.
  // Android: also declared via intent-filter (generated by `npx cap sync`).
  // iOS: registered from this value.
  ios: {
    scheme: 'com.barakah.services',
    // Preserve native safe-area insets for the WebView. The web UI consumes
    // them with CSS env(safe-area-inset-*), which prevents content from
    // rendering underneath the system status bar, notch, or Dynamic Island.
    contentInset: 'automatic',
  },
  android: {
    // Safe-area insets are automatically respected by Capacitor WebView
    // on Android, ensuring content doesn't overlap with system UI
  },
  plugins: {
    LocalNotifications: {
      presentationOptions: ['badge', 'sound', 'banner', 'list'],
    },
  },
};

export default config;
