import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.barakah.services',
  appName: 'Barakah',
  webDir: 'dist',
  // Custom URL scheme used by the native OAuth deep link callback.
  // Android: also declared via intent-filter (generated by `npx cap sync`).
  // iOS: registered from this value.
  ios: {
    scheme: 'com.barakah.services',
  },
};

export default config;
