import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ur' | 'ar' | 'tr' | 'id' | 'ms' | 'ta' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  direction: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Login/Register page
    'login.create_account': 'Create an account',
    'login.enter_email': 'Enter your email to signup for this app',
    'login.email_placeholder': 'yourname@email.com',
    'login.continue': 'Continue',
    'login.or': 'or',
    'login.google': 'Continue with Google',
    'login.apple': 'Continue with Apple',
    'login.terms': 'By continuing, you agree to our',
    'login.terms_of_service': 'Terms of Service',
    'login.and': 'and',
    'login.privacy_policy': 'Privacy Policy',
    'login.tagline': 'FAITH. LIFESTYLE. COMMUNITY.',
    'login.choose_profile': 'Choose Your Profile',
    'login.select_account_type': 'Select the type of account you want to create',
    'login.normal_user': 'Normal User',
    'login.normal_user_desc': 'Browse and purchase products & tours',
    'login.seller': 'Seller',
    'login.seller_desc': 'List and sell your products',
    'login.travel_partner': 'Travel Partner',
    'login.travel_partner_desc': 'Offer tour packages to users',
    'login.already_have_account': 'Already have an account?',
    'login.sign_in': 'Sign In',
    'login.sign_up': 'Sign Up',
    'login.welcome_back': 'Welcome Back',
    'login.enter_credentials': 'Enter your credentials to sign in',
    'login.create_your_account': 'Create Your Account',
    'login.sign_up_as': 'Sign up as',
    'login.full_name': 'Full Name',
    'login.password': 'Password',
    'login.create_account_btn': 'Create Account',
    'login.back': 'Back',
    'login.dont_have_account': "Don't have an account?",
    'login.please_wait': 'Please wait...',
    
    // Home page
    'home.greeting': 'As-Salaam-Alaikum',
    'home.title': 'Barakah Home',
    'home.getting_location': 'Getting location...',
    'home.tap_retry': 'Tap to retry',
    'home.current_time': 'Current Time',
    'home.next_prayer': 'Next Prayer',
    'home.next_prayer_at': 'Next prayer at',
    
    // Prayer names
    'prayer.fajr': 'Fajr',
    'prayer.dhuhr': 'Dhuhr',
    'prayer.asr': 'Asr',
    'prayer.maghrib': 'Maghrib',
    'prayer.isha': 'Isha',
    'prayer.upcoming': 'Upcoming',
    'prayer.time': 'Time',
    'prayer.next': 'Next',
    
    // Quick actions
    'action.qibla': 'Qibla',
    'action.quran': 'Quran',
    'action.mood': "Dua's",
    'action.makkah_live': 'Makkah Live',
    'action.prayer': 'Prayer',
    'action.zakat': 'Zakat',
    'action.scanner': 'Scanner',
    'action.travel': 'Travel',
    
    // Bottom Navigation
    'nav.home': 'Home',
    'nav.store': 'Marketplace',
    'nav.guftagu': 'Guftagu',
    'nav.places': 'Places',
    'nav.account': 'Account',
    'nav.prayer': 'Prayer',
    'nav.scanner': 'Scanner',
    
    // News page
    'news.title': 'Islamic News',
    'news.subtitle': 'Stay informed with the latest updates',
    'news.load_more': 'Load More',
    'news.category.all': 'All',
    'news.category.world': 'World',
    'news.category.education': 'Education',
    'news.category.community': 'Community',
    'news.category.charity': 'Charity',
    'news.category.business': 'Business',
    
    // Mood page
    'mood.title': 'How Are You?',
    'mood.subtitle': 'Select your mood for guidance',
    'mood.how_feeling': 'How are you feeling today?',
    'mood.very_low': 'Very Low',
    'mood.low': 'Low',
    'mood.neutral': 'Okay',
    'mood.good': 'Good',
    'mood.excellent': 'Great',
    'mood.scale_low': 'Low',
    'mood.scale_high': 'High',
    'mood.try_again': 'Back',
    'mood.new_quote': 'New Quote',
    
    // Menu
    'menu.home': 'Home',
    'menu.prayer_times': 'Prayer Times',
    'menu.qibla': 'Qibla',
    'menu.quran': 'Quran',
    'menu.makkah_live': 'Makkah Live',
    'menu.zakat': 'Zakat Calculator',
    'menu.shop': 'Shop',
    'menu.progress': 'Progress',
    'menu.account': 'Account',
    'menu.sign_out': 'Sign Out',
    
    // Language selector
    'language.select': 'Select Language',
    'language.english': 'English',
    'language.urdu': 'Urdu',
    'language.arabic': 'Arabic',
    'language.turkish': 'Turkish',
    'language.indonesian': 'Indonesian',
    'language.malay': 'Malay',
    'language.tamil': 'Tamil',
    'language.bengali': 'Bengali',
    'languageSelector.title': 'Language',
  },
  ur: {
    // Login/Register page
    'login.create_account': 'اکاؤنٹ بنائیں',
    'login.enter_email': 'اس ایپ کے لیے اپنا ای میل درج کریں',
    'login.email_placeholder': 'آپ کا نام@ای میل.کوم',
    'login.continue': 'جاری رکھیں',
    'login.or': 'یا',
    'login.google': 'گوگل کے ساتھ جاری رکھیں',
    'login.apple': 'ایپل کے ساتھ جاری رکھیں',
    'login.terms': 'جاری رکھنے سے آپ ہماری',
    'login.terms_of_service': 'سروس کی شرائط',
    'login.and': 'اور',
    'login.privacy_policy': 'رازداری کی پالیسی',
    'login.tagline': 'ایمان. طرز زندگی. کمیونٹی.',
    'login.choose_profile': 'اپنا پروفائل منتخب کریں',
    'login.select_account_type': 'اکاؤنٹ کی قسم منتخب کریں جو آپ بنانا چاہتے ہیں',
    'login.normal_user': 'عام صارف',
    'login.normal_user_desc': 'مصنوعات اور ٹورز براؤز کریں اور خریدیں',
    'login.seller': 'بیچنے والا',
    'login.seller_desc': 'اپنی مصنوعات کی فہرست بنائیں اور بیچیں',
    'login.travel_partner': 'ٹریول پارٹنر',
    'login.travel_partner_desc': 'صارفین کو ٹور پیکجز پیش کریں',
    'login.already_have_account': 'پہلے سے اکاؤنٹ ہے؟',
    'login.sign_in': 'سائن ان',
    'login.sign_up': 'سائن اپ',
    'login.welcome_back': 'واپس خوش آمدید',
    'login.enter_credentials': 'سائن ان کرنے کے لیے اپنی معلومات درج کریں',
    'login.create_your_account': 'اپنا اکاؤنٹ بنائیں',
    'login.sign_up_as': 'بطور سائن اپ کریں',
    'login.full_name': 'پورا نام',
    'login.password': 'پاس ورڈ',
    'login.create_account_btn': 'اکاؤنٹ بنائیں',
    'login.back': 'واپس',
    'login.dont_have_account': 'اکاؤنٹ نہیں ہے؟',
    'login.please_wait': 'براہ کرم انتظار کریں...',
    
    // Home page
    'home.greeting': 'السلام علیکم',
    'home.title': 'برکت ہوم',
    'home.getting_location': 'مقام حاصل کیا جا رہا ہے...',
    'home.tap_retry': 'دوبارہ کوشش کریں',
    'home.current_time': 'موجودہ وقت',
    'home.next_prayer': 'اگلی نماز',
    'home.next_prayer_at': 'اگلی نماز',
    
    // Prayer names
    'prayer.fajr': 'فجر',
    'prayer.dhuhr': 'ظہر',
    'prayer.asr': 'عصر',
    'prayer.maghrib': 'مغرب',
    'prayer.isha': 'عشاء',
    'prayer.upcoming': 'آنے والی',
    'prayer.time': 'وقت',
    'prayer.next': 'اگلی',
    
    // Quick actions
    'action.qibla': 'قبلہ',
    'action.quran': 'قرآن',
    'action.mood': 'دعا',
    'action.makkah_live': 'مکہ لائیو',
    'action.prayer': 'نماز',
    'action.zakat': 'زکوٰۃ',
    'action.scanner': 'اسکینر',
    'action.travel': 'سفر',
    
    // Bottom Navigation
    'nav.home': 'ہوم',
    'nav.store': 'مارکیٹ',
    'nav.guftagu': 'گفتگو',
    'nav.places': 'مقامات',
    'nav.account': 'اکاؤنٹ',
    'nav.prayer': 'نماز',
    'nav.scanner': 'اسکینر',
    
    // News page
    'news.title': 'اسلامی خبریں',
    'news.subtitle': 'تازہ ترین اپڈیٹس سے آگاہ رہیں',
    'news.load_more': 'مزید لوڈ کریں',
    'news.category.all': 'سب',
    'news.category.world': 'دنیا',
    'news.category.education': 'تعلیم',
    'news.category.community': 'کمیونٹی',
    'news.category.charity': 'خیرات',
    'news.category.business': 'کاروبار',
    
    // Mood page
    'mood.title': 'آپ کیسے ہیں؟',
    'mood.subtitle': 'رہنمائی کے لیے اپنا موڈ منتخب کریں',
    'mood.how_feeling': 'آج آپ کا موڈ کیسا ہے؟',
    'mood.very_low': 'بہت کم',
    'mood.low': 'کم',
    'mood.neutral': 'ٹھیک',
    'mood.good': 'اچھا',
    'mood.excellent': 'بہترین',
    'mood.scale_low': 'کم',
    'mood.scale_high': 'زیادہ',
    'mood.try_again': 'واپس',
    'mood.new_quote': 'نیا اقتباس',
    
    // Menu
    'menu.home': 'ہوم',
    'menu.prayer_times': 'نماز کے اوقات',
    'menu.qibla': 'قبلہ',
    'menu.quran': 'قرآن',
    'menu.makkah_live': 'مکہ لائیو',
    'menu.zakat': 'زکوٰۃ کیلکولیٹر',
    'menu.shop': 'دکان',
    'menu.progress': 'پیش رفت',
    'menu.account': 'اکاؤنٹ',
    'menu.sign_out': 'سائن آؤٹ',
    
    // Language selector
    'language.select': 'زبان منتخب کریں',
    'language.english': 'انگریزی',
    'language.urdu': 'اردو',
    'language.arabic': 'عربی',
    'language.turkish': 'ترکی',
    'language.indonesian': 'انڈونیشی',
    'language.malay': 'مالے',
    'language.tamil': 'تامل',
    'language.bengali': 'بنگالی',
    'languageSelector.title': 'زبان',
  },
  ar: {
    // Login/Register page
    'login.create_account': 'إنشاء حساب',
    'login.enter_email': 'أدخل بريدك الإلكتروني للتسجيل',
    'login.email_placeholder': 'اسمك@البريد.كوم',
    'login.continue': 'متابعة',
    'login.or': 'أو',
    'login.google': 'المتابعة مع جوجل',
    'login.apple': 'المتابعة مع أبل',
    'login.terms': 'بالمتابعة، فإنك توافق على',
    'login.terms_of_service': 'شروط الخدمة',
    'login.and': 'و',
    'login.privacy_policy': 'سياسة الخصوصية',
    'login.tagline': 'الإيمان. أسلوب الحياة. المجتمع.',
    'login.choose_profile': 'اختر ملفك الشخصي',
    'login.select_account_type': 'حدد نوع الحساب الذي تريد إنشاءه',
    'login.normal_user': 'مستخدم عادي',
    'login.normal_user_desc': 'تصفح وشراء المنتجات والجولات',
    'login.seller': 'بائع',
    'login.seller_desc': 'قم بإدراج وبيع منتجاتك',
    'login.travel_partner': 'شريك السفر',
    'login.travel_partner_desc': 'قدم باقات سياحية للمستخدمين',
    'login.already_have_account': 'لديك حساب بالفعل؟',
    'login.sign_in': 'تسجيل الدخول',
    'login.sign_up': 'التسجيل',
    'login.welcome_back': 'مرحباً بعودتك',
    'login.enter_credentials': 'أدخل بياناتك لتسجيل الدخول',
    'login.create_your_account': 'أنشئ حسابك',
    'login.sign_up_as': 'التسجيل كـ',
    'login.full_name': 'الاسم الكامل',
    'login.password': 'كلمة المرور',
    'login.create_account_btn': 'إنشاء حساب',
    'login.back': 'رجوع',
    'login.dont_have_account': 'ليس لديك حساب؟',
    'login.please_wait': 'يرجى الانتظار...',
    
    // Home page
    'home.greeting': 'السلام عليكم',
    'home.title': 'بركة الرئيسية',
    'home.getting_location': 'جارٍ تحديد الموقع...',
    'home.tap_retry': 'انقر لإعادة المحاولة',
    'home.current_time': 'الوقت الحالي',
    'home.next_prayer': 'الصلاة التالية',
    'home.next_prayer_at': 'الصلاة التالية',
    
    // Prayer names
    'prayer.fajr': 'الفجر',
    'prayer.dhuhr': 'الظهر',
    'prayer.asr': 'العصر',
    'prayer.maghrib': 'المغرب',
    'prayer.isha': 'العشاء',
    'prayer.upcoming': 'القادمة',
    'prayer.time': 'وقت',
    'prayer.next': 'التالية',
    
    // Quick actions
    'action.qibla': 'القبلة',
    'action.quran': 'القرآن',
    'action.mood': 'دعاء',
    'action.makkah_live': 'مكة مباشر',
    'action.prayer': 'الصلاة',
    'action.zakat': 'الزكاة',
    'action.scanner': 'ماسح',
    'action.travel': 'السفر',
    
    // Bottom Navigation
    'nav.home': 'الرئيسية',
    'nav.store': 'المتجر',
    'nav.guftagu': 'گفتگو',
    'nav.places': 'الأماكن',
    'nav.account': 'الحساب',
    'nav.prayer': 'الصلاة',
    'nav.scanner': 'الماسح الضوئي',
    
    // News page
    'news.title': 'الأخبار الإسلامية',
    'news.subtitle': 'ابق على اطلاع بآخر التحديثات',
    'news.load_more': 'تحميل المزيد',
    'news.category.all': 'الكل',
    'news.category.world': 'العالم',
    'news.category.education': 'التعليم',
    'news.category.community': 'المجتمع',
    'news.category.charity': 'الخيرية',
    'news.category.business': 'الأعمال',
    
    // Mood page
    'mood.title': 'كيف حالك؟',
    'mood.subtitle': 'اختر مزاجك للإرشاد',
    'mood.how_feeling': 'كيف تشعر اليوم؟',
    'mood.very_low': 'منخفض جداً',
    'mood.low': 'منخفض',
    'mood.neutral': 'عادي',
    'mood.good': 'جيد',
    'mood.excellent': 'ممتاز',
    'mood.scale_low': 'منخفض',
    'mood.scale_high': 'مرتفع',
    'mood.try_again': 'رجوع',
    'mood.new_quote': 'اقتباس جديد',
    
    // Menu
    'menu.home': 'الرئيسية',
    'menu.prayer_times': 'أوقات الصلاة',
    'menu.qibla': 'القبلة',
    'menu.quran': 'القرآن',
    'menu.makkah_live': 'مكة مباشر',
    'menu.zakat': 'حاسبة الزكاة',
    'menu.shop': 'المتجر',
    'menu.progress': 'التقدم',
    'menu.account': 'الحساب',
    'menu.sign_out': 'تسجيل الخروج',
    
    // Language selector
    'language.select': 'اختر اللغة',
    'language.english': 'الإنجليزية',
    'language.urdu': 'الأردية',
    'language.arabic': 'العربية',
    'language.turkish': 'التركية',
    'language.indonesian': 'الإندونيسية',
    'language.malay': 'الملايو',
    'language.tamil': 'التاميلية',
    'language.bengali': 'البنغالية',
    'languageSelector.title': 'اللغة',
  },
  tr: {
    // Login/Register page
    'login.create_account': 'Hesap oluştur',
    'login.enter_email': 'Bu uygulamaya kaydolmak için e-postanızı girin',
    'login.email_placeholder': 'isminiz@email.com',
    'login.continue': 'Devam et',
    'login.or': 'veya',
    'login.google': 'Google ile devam et',
    'login.apple': 'Apple ile devam et',
    'login.terms': 'Devam ederek şunları kabul edersiniz',
    'login.terms_of_service': 'Hizmet Şartları',
    'login.and': 've',
    'login.privacy_policy': 'Gizlilik Politikası',
    'login.tagline': 'İMAN. YAŞAM TARZI. TOPLULUK.',
    'login.choose_profile': 'Profilinizi Seçin',
    'login.select_account_type': 'Oluşturmak istediğiniz hesap türünü seçin',
    'login.normal_user': 'Normal Kullanıcı',
    'login.normal_user_desc': 'Ürün ve turları incele ve satın al',
    'login.seller': 'Satıcı',
    'login.seller_desc': 'Ürünlerinizi listeleyin ve satın',
    'login.travel_partner': 'Seyahat Ortağı',
    'login.travel_partner_desc': 'Kullanıcılara tur paketleri sunun',
    'login.already_have_account': 'Zaten hesabınız var mı?',
    'login.sign_in': 'Giriş Yap',
    'login.sign_up': 'Kaydol',
    'login.welcome_back': 'Tekrar Hoş Geldiniz',
    'login.enter_credentials': 'Giriş yapmak için bilgilerinizi girin',
    'login.create_your_account': 'Hesabınızı Oluşturun',
    'login.sign_up_as': 'Olarak kaydol',
    'login.full_name': 'Tam Ad',
    'login.password': 'Şifre',
    'login.create_account_btn': 'Hesap Oluştur',
    'login.back': 'Geri',
    'login.dont_have_account': 'Hesabınız yok mu?',
    'login.please_wait': 'Lütfen bekleyin...',
    
    // Home page
    'home.greeting': 'Selamün Aleyküm',
    'home.title': 'Bereket Ana Sayfa',
    'home.getting_location': 'Konum alınıyor...',
    'home.tap_retry': 'Tekrar denemek için dokunun',
    'home.current_time': 'Şu Anki Zaman',
    'home.next_prayer': 'Sonraki Namaz',
    'home.next_prayer_at': 'Sonraki namaz',
    
    // Prayer names
    'prayer.fajr': 'Sabah',
    'prayer.dhuhr': 'Öğle',
    'prayer.asr': 'İkindi',
    'prayer.maghrib': 'Akşam',
    'prayer.isha': 'Yatsı',
    'prayer.upcoming': 'Yaklaşan',
    'prayer.time': 'Zaman',
    'prayer.next': 'Sonraki',
    
    // Quick actions
    'action.qibla': 'Kıble',
    'action.quran': 'Kuran',
    'action.mood': 'Dua',
    'action.makkah_live': 'Mekke Canlı',
    'action.prayer': 'Namaz',
    'action.zakat': 'Zekat',
    'action.scanner': 'Tarayıcı',
    'action.travel': 'Seyahat',
    
    // Bottom Navigation
    'nav.home': 'Ana Sayfa',
    'nav.store': 'Mağaza',
    'nav.guftagu': 'Guftagu',
    'nav.places': 'Yerler',
    'nav.account': 'Hesap',
    'nav.prayer': 'Namaz',
    'nav.scanner': 'Tarayıcı',
    
    // News page
    'news.title': 'İslami Haberler',
    'news.subtitle': 'En son güncellemelerden haberdar olun',
    'news.load_more': 'Daha Fazla Yükle',
    'news.category.all': 'Tümü',
    'news.category.world': 'Dünya',
    'news.category.education': 'Eğitim',
    'news.category.community': 'Topluluk',
    'news.category.charity': 'Hayır',
    'news.category.business': 'İş',
    
    // Mood page
    'mood.title': 'Nasılsınız?',
    'mood.subtitle': 'Rehberlik için ruh halinizi seçin',
    'mood.how_feeling': 'Bugün nasıl hissediyorsunuz?',
    'mood.very_low': 'Çok Düşük',
    'mood.low': 'Düşük',
    'mood.neutral': 'Normal',
    'mood.good': 'İyi',
    'mood.excellent': 'Harika',
    'mood.scale_low': 'Düşük',
    'mood.scale_high': 'Yüksek',
    'mood.try_again': 'Geri',
    'mood.new_quote': 'Yeni Alıntı',
    
    // Menu
    'menu.home': 'Ana Sayfa',
    'menu.prayer_times': 'Namaz Vakitleri',
    'menu.qibla': 'Kıble',
    'menu.quran': 'Kuran',
    'menu.makkah_live': 'Mekke Canlı',
    'menu.zakat': 'Zekat Hesaplayıcı',
    'menu.shop': 'Mağaza',
    'menu.progress': 'İlerleme',
    'menu.account': 'Hesap',
    'menu.sign_out': 'Çıkış Yap',
    
    // Language selector
    'language.select': 'Dil Seçin',
    'language.english': 'İngilizce',
    'language.urdu': 'Urduca',
    'language.arabic': 'Arapça',
    'language.turkish': 'Türkçe',
    'language.indonesian': 'Endonezce',
    'language.malay': 'Malayca',
    'language.tamil': 'Tamilce',
    'language.bengali': 'Bengalce',
    'languageSelector.title': 'Dil',
  },
  id: {
    // Login/Register page
    'login.create_account': 'Buat akun',
    'login.enter_email': 'Masukkan email Anda untuk mendaftar',
    'login.email_placeholder': 'namaanda@email.com',
    'login.continue': 'Lanjutkan',
    'login.or': 'atau',
    'login.google': 'Lanjutkan dengan Google',
    'login.apple': 'Lanjutkan dengan Apple',
    'login.terms': 'Dengan melanjutkan, Anda menyetujui',
    'login.terms_of_service': 'Ketentuan Layanan',
    'login.and': 'dan',
    'login.privacy_policy': 'Kebijakan Privasi',
    'login.tagline': 'IMAN. GAYA HIDUP. KOMUNITAS.',
    'login.choose_profile': 'Pilih Profil Anda',
    'login.select_account_type': 'Pilih jenis akun yang ingin Anda buat',
    'login.normal_user': 'Pengguna Biasa',
    'login.normal_user_desc': 'Jelajahi dan beli produk & tur',
    'login.seller': 'Penjual',
    'login.seller_desc': 'Daftarkan dan jual produk Anda',
    'login.travel_partner': 'Mitra Perjalanan',
    'login.travel_partner_desc': 'Tawarkan paket tur kepada pengguna',
    'login.already_have_account': 'Sudah punya akun?',
    'login.sign_in': 'Masuk',
    'login.sign_up': 'Daftar',
    'login.welcome_back': 'Selamat Datang Kembali',
    'login.enter_credentials': 'Masukkan kredensial Anda untuk masuk',
    'login.create_your_account': 'Buat Akun Anda',
    'login.sign_up_as': 'Daftar sebagai',
    'login.full_name': 'Nama Lengkap',
    'login.password': 'Kata Sandi',
    'login.create_account_btn': 'Buat Akun',
    'login.back': 'Kembali',
    'login.dont_have_account': 'Belum punya akun?',
    'login.please_wait': 'Harap tunggu...',
    
    // Home page
    'home.greeting': 'Assalamualaikum',
    'home.title': 'Beranda Barakah',
    'home.getting_location': 'Mendapatkan lokasi...',
    'home.tap_retry': 'Ketuk untuk coba lagi',
    'home.current_time': 'Waktu Sekarang',
    'home.next_prayer': 'Shalat Berikutnya',
    'home.next_prayer_at': 'Shalat berikutnya pada',
    
    // Prayer names
    'prayer.fajr': 'Subuh',
    'prayer.dhuhr': 'Dzuhur',
    'prayer.asr': 'Ashar',
    'prayer.maghrib': 'Maghrib',
    'prayer.isha': 'Isya',
    'prayer.upcoming': 'Mendatang',
    'prayer.time': 'Waktu',
    'prayer.next': 'Berikutnya',
    
    // Quick actions
    'action.qibla': 'Kiblat',
    'action.quran': 'Quran',
    'action.mood': 'Doa',
    'action.makkah_live': 'Mekah Live',
    'action.prayer': 'Shalat',
    'action.zakat': 'Zakat',
    'action.scanner': 'Pemindai',
    'action.travel': 'Perjalanan',
    
    // Bottom Navigation
    'nav.home': 'Beranda',
    'nav.store': 'Toko',
    'nav.guftagu': 'Guftagu',
    'nav.places': 'Tempat',
    'nav.account': 'Akun',
    'nav.prayer': 'Shalat',
    'nav.scanner': 'Pemindai',
    
    // News page
    'news.title': 'Berita Islam',
    'news.subtitle': 'Tetap terinformasi dengan pembaruan terbaru',
    'news.load_more': 'Muat Lebih Banyak',
    'news.category.all': 'Semua',
    'news.category.world': 'Dunia',
    'news.category.education': 'Pendidikan',
    'news.category.community': 'Komunitas',
    'news.category.charity': 'Amal',
    'news.category.business': 'Bisnis',
    
    // Mood page
    'mood.title': 'Bagaimana Kabarmu?',
    'mood.subtitle': 'Pilih suasana hati untuk bimbingan',
    'mood.how_feeling': 'Bagaimana perasaanmu hari ini?',
    'mood.very_low': 'Sangat Rendah',
    'mood.low': 'Rendah',
    'mood.neutral': 'Biasa',
    'mood.good': 'Baik',
    'mood.excellent': 'Sangat Baik',
    'mood.scale_low': 'Rendah',
    'mood.scale_high': 'Tinggi',
    'mood.try_again': 'Kembali',
    'mood.new_quote': 'Kutipan Baru',
    
    // Menu
    'menu.home': 'Beranda',
    'menu.prayer_times': 'Waktu Shalat',
    'menu.qibla': 'Kiblat',
    'menu.quran': 'Quran',
    'menu.makkah_live': 'Mekah Live',
    'menu.zakat': 'Kalkulator Zakat',
    'menu.shop': 'Toko',
    'menu.progress': 'Kemajuan',
    'menu.account': 'Akun',
    'menu.sign_out': 'Keluar',
    
    // Language selector
    'language.select': 'Pilih Bahasa',
    'language.english': 'Inggris',
    'language.urdu': 'Urdu',
    'language.arabic': 'Arab',
    'language.turkish': 'Turki',
    'language.indonesian': 'Indonesia',
    'language.malay': 'Melayu',
    'language.tamil': 'Tamil',
    'language.bengali': 'Bengali',
    'languageSelector.title': 'Bahasa',
  },
  ms: {
    // Login/Register page
    'login.create_account': 'Buat akaun',
    'login.enter_email': 'Masukkan e-mel anda untuk mendaftar',
    'login.email_placeholder': 'namaanda@email.com',
    'login.continue': 'Teruskan',
    'login.or': 'atau',
    'login.google': 'Teruskan dengan Google',
    'login.apple': 'Teruskan dengan Apple',
    'login.terms': 'Dengan meneruskan, anda bersetuju dengan',
    'login.terms_of_service': 'Terma Perkhidmatan',
    'login.and': 'dan',
    'login.privacy_policy': 'Dasar Privasi',
    'login.tagline': 'IMAN. GAYA HIDUP. KOMUNITI.',
    'login.choose_profile': 'Pilih Profil Anda',
    'login.select_account_type': 'Pilih jenis akaun yang ingin anda buat',
    'login.normal_user': 'Pengguna Biasa',
    'login.normal_user_desc': 'Layari dan beli produk & lawatan',
    'login.seller': 'Penjual',
    'login.seller_desc': 'Senaraikan dan jual produk anda',
    'login.travel_partner': 'Rakan Perjalanan',
    'login.travel_partner_desc': 'Tawarkan pakej lawatan kepada pengguna',
    'login.already_have_account': 'Sudah mempunyai akaun?',
    'login.sign_in': 'Log Masuk',
    'login.sign_up': 'Daftar',
    'login.welcome_back': 'Selamat Kembali',
    'login.enter_credentials': 'Masukkan kelayakan anda untuk log masuk',
    'login.create_your_account': 'Buat Akaun Anda',
    'login.sign_up_as': 'Daftar sebagai',
    'login.full_name': 'Nama Penuh',
    'login.password': 'Kata Laluan',
    'login.create_account_btn': 'Buat Akaun',
    'login.back': 'Kembali',
    'login.dont_have_account': 'Tiada akaun?',
    'login.please_wait': 'Sila tunggu...',
    
    // Home page
    'home.greeting': 'Assalamualaikum',
    'home.title': 'Laman Utama Barakah',
    'home.getting_location': 'Mendapatkan lokasi...',
    'home.tap_retry': 'Ketuk untuk cuba lagi',
    'home.current_time': 'Masa Semasa',
    'home.next_prayer': 'Solat Seterusnya',
    'home.next_prayer_at': 'Solat seterusnya pada',
    
    // Prayer names
    'prayer.fajr': 'Subuh',
    'prayer.dhuhr': 'Zohor',
    'prayer.asr': 'Asar',
    'prayer.maghrib': 'Maghrib',
    'prayer.isha': 'Isyak',
    'prayer.upcoming': 'Akan Datang',
    'prayer.time': 'Masa',
    'prayer.next': 'Seterusnya',
    
    // Quick actions
    'action.qibla': 'Kiblat',
    'action.quran': 'Quran',
    'action.mood': 'Doa',
    'action.makkah_live': 'Mekah Live',
    'action.prayer': 'Solat',
    'action.zakat': 'Zakat',
    'action.scanner': 'Pengimbas',
    'action.travel': 'Perjalanan',
    
    // Bottom Navigation
    'nav.home': 'Utama',
    'nav.store': 'Kedai',
    'nav.guftagu': 'Guftagu',
    'nav.places': 'Tempat',
    'nav.account': 'Akaun',
    'nav.prayer': 'Solat',
    'nav.scanner': 'Pengimbas',
    
    // News page
    'news.title': 'Berita Islam',
    'news.subtitle': 'Terus mendapat maklumat dengan kemas kini terkini',
    'news.load_more': 'Muat Lagi',
    'news.category.all': 'Semua',
    'news.category.world': 'Dunia',
    'news.category.education': 'Pendidikan',
    'news.category.community': 'Komuniti',
    'news.category.charity': 'Amal',
    'news.category.business': 'Perniagaan',
    
    // Mood page
    'mood.title': 'Apa Khabar?',
    'mood.subtitle': 'Pilih suasana hati untuk bimbingan',
    'mood.how_feeling': 'Bagaimana perasaan anda hari ini?',
    'mood.very_low': 'Sangat Rendah',
    'mood.low': 'Rendah',
    'mood.neutral': 'Biasa',
    'mood.good': 'Baik',
    'mood.excellent': 'Sangat Baik',
    'mood.scale_low': 'Rendah',
    'mood.scale_high': 'Tinggi',
    'mood.try_again': 'Kembali',
    'mood.new_quote': 'Petikan Baru',
    
    // Menu
    'menu.home': 'Utama',
    'menu.prayer_times': 'Waktu Solat',
    'menu.qibla': 'Kiblat',
    'menu.quran': 'Quran',
    'menu.makkah_live': 'Mekah Live',
    'menu.zakat': 'Kalkulator Zakat',
    'menu.shop': 'Kedai',
    'menu.progress': 'Kemajuan',
    'menu.account': 'Akaun',
    'menu.sign_out': 'Log Keluar',
    
    // Language selector
    'language.select': 'Pilih Bahasa',
    'language.english': 'Inggeris',
    'language.urdu': 'Urdu',
    'language.arabic': 'Arab',
    'language.turkish': 'Turki',
    'language.indonesian': 'Indonesia',
    'language.malay': 'Melayu',
    'language.tamil': 'Tamil',
    'language.bengali': 'Bengali',
    'languageSelector.title': 'Bahasa',
  },
  ta: {
    // Login/Register page
    'login.create_account': 'கணக்கை உருவாக்கு',
    'login.enter_email': 'பதிவு செய்ய உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    'login.email_placeholder': 'உங்கள்பெயர்@email.com',
    'login.continue': 'தொடரவும்',
    'login.or': 'அல்லது',
    'login.google': 'Google உடன் தொடரவும்',
    'login.apple': 'Apple உடன் தொடரவும்',
    'login.terms': 'தொடர்வதன் மூலம், நீங்கள் ஒப்புக்கொள்கிறீர்கள்',
    'login.terms_of_service': 'சேவை விதிமுறைகள்',
    'login.and': 'மற்றும்',
    'login.privacy_policy': 'தனியுரிமை கொள்கை',
    'login.tagline': 'நம்பிக்கை. வாழ்க்கை முறை. சமூகம்.',
    'login.choose_profile': 'உங்கள் சுயவிவரத்தைத் தேர்ந்தெடுக்கவும்',
    'login.select_account_type': 'நீங்கள் உருவாக்க விரும்பும் கணக்கு வகையைத் தேர்ந்தெடுக்கவும்',
    'login.normal_user': 'சாதாரண பயனர்',
    'login.normal_user_desc': 'பொருட்கள் மற்றும் சுற்றுலாக்களை உலாவி வாங்கவும்',
    'login.seller': 'விற்பனையாளர்',
    'login.seller_desc': 'உங்கள் பொருட்களை பட்டியலிட்டு விற்கவும்',
    'login.travel_partner': 'பயண பங்காளி',
    'login.travel_partner_desc': 'பயனர்களுக்கு சுற்றுலா தொகுப்புகளை வழங்கவும்',
    'login.already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா?',
    'login.sign_in': 'உள்நுழை',
    'login.sign_up': 'பதிவு செய்',
    'login.welcome_back': 'மீண்டும் வரவேற்கிறோம்',
    'login.enter_credentials': 'உள்நுழைய உங்கள் சான்றுகளை உள்ளிடவும்',
    'login.create_your_account': 'உங்கள் கணக்கை உருவாக்கவும்',
    'login.sign_up_as': 'இவராக பதிவு செய்',
    'login.full_name': 'முழு பெயர்',
    'login.password': 'கடவுச்சொல்',
    'login.create_account_btn': 'கணக்கை உருவாக்கு',
    'login.back': 'பின்',
    'login.dont_have_account': 'கணக்கு இல்லையா?',
    'login.please_wait': 'தயவுசெய்து காத்திருங்கள்...',
    
    // Home page
    'home.greeting': 'அஸ்ஸலாமு அலைக்கும்',
    'home.title': 'பரக்காஹ் முகப்பு',
    'home.getting_location': 'இருப்பிடம் பெறப்படுகிறது...',
    'home.tap_retry': 'மீண்டும் முயற்சிக்க தட்டவும்',
    'home.current_time': 'தற்போதைய நேரம்',
    'home.next_prayer': 'அடுத்த தொழுகை',
    'home.next_prayer_at': 'அடுத்த தொழுகை',
    
    // Prayer names
    'prayer.fajr': 'ஃபஜ்ர்',
    'prayer.dhuhr': 'துஹ்ர்',
    'prayer.asr': 'அஸர்',
    'prayer.maghrib': 'மஃரிப்',
    'prayer.isha': 'இஷா',
    'prayer.upcoming': 'வரவிருக்கும்',
    'prayer.time': 'நேரம்',
    'prayer.next': 'அடுத்தது',
    
    // Quick actions
    'action.qibla': 'கிப்லா',
    'action.quran': 'குர்ஆன்',
    'action.mood': 'துஆ',
    'action.makkah_live': 'மக்கா நேரலை',
    'action.prayer': 'தொழுகை',
    'action.zakat': 'ஜகாத்',
    'action.scanner': 'ஸ்கேனர்',
    'action.travel': 'பயணம்',
    
    // Bottom Navigation
    'nav.home': 'முகப்பு',
    'nav.store': 'கடை',
    'nav.guftagu': 'Guftagu',
    'nav.places': 'இடங்கள்',
    'nav.account': 'கணக்கு',
    'nav.prayer': 'தொழுகை',
    'nav.scanner': 'ஸ்கேனர்',
    
    // News page
    'news.title': 'இஸ்லாமிய செய்திகள்',
    'news.subtitle': 'சமீபத்திய புதுப்பிப்புகளுடன் தகவல் பெறுங்கள்',
    'news.load_more': 'மேலும் ஏற்று',
    'news.category.all': 'அனைத்தும்',
    'news.category.world': 'உலகம்',
    'news.category.education': 'கல்வி',
    'news.category.community': 'சமூகம்',
    'news.category.charity': 'தர்மம்',
    'news.category.business': 'வணிகம்',
    
    // Mood page
    'mood.title': 'எப்படி இருக்கிறீர்கள்?',
    'mood.subtitle': 'வழிகாட்டுதலுக்கு உங்கள் மனநிலையைத் தேர்ந்தெடுக்கவும்',
    'mood.how_feeling': 'இன்று எப்படி உணர்கிறீர்கள்?',
    'mood.very_low': 'மிகக் குறைவு',
    'mood.low': 'குறைவு',
    'mood.neutral': 'சாதாரண',
    'mood.good': 'நல்ல',
    'mood.excellent': 'சிறந்த',
    'mood.scale_low': 'குறைவு',
    'mood.scale_high': 'அதிகம்',
    'mood.try_again': 'பின்',
    'mood.new_quote': 'புதிய மேற்கோள்',
    
    // Menu
    'menu.home': 'முகப்பு',
    'menu.prayer_times': 'தொழுகை நேரங்கள்',
    'menu.qibla': 'கிப்லா',
    'menu.quran': 'குர்ஆன்',
    'menu.makkah_live': 'மக்கா நேரலை',
    'menu.zakat': 'ஜகாத் கணக்கி',
    'menu.shop': 'கடை',
    'menu.progress': 'முன்னேற்றம்',
    'menu.account': 'கணக்கு',
    'menu.sign_out': 'வெளியேறு',
    
    // Language selector
    'language.select': 'மொழியைத் தேர்ந்தெடுக்கவும்',
    'language.english': 'ஆங்கிலம்',
    'language.urdu': 'உருது',
    'language.arabic': 'அரபு',
    'language.turkish': 'துருக்கி',
    'language.indonesian': 'இந்தோனேசிய',
    'language.malay': 'மலாய்',
    'language.tamil': 'தமிழ்',
    'language.bengali': 'வங்காளம்',
    'languageSelector.title': 'மொழி',
  },
  bn: {
    // Login/Register page
    'login.create_account': 'একটি অ্যাকাউন্ট তৈরি করুন',
    'login.enter_email': 'সাইন আপ করতে আপনার ইমেল লিখুন',
    'login.email_placeholder': 'আপনারনাম@email.com',
    'login.continue': 'চালিয়ে যান',
    'login.or': 'অথবা',
    'login.google': 'Google দিয়ে চালিয়ে যান',
    'login.apple': 'Apple দিয়ে চালিয়ে যান',
    'login.terms': 'চালিয়ে যাওয়ার মাধ্যমে, আপনি সম্মত হচ্ছেন',
    'login.terms_of_service': 'সেবার শর্তাবলী',
    'login.and': 'এবং',
    'login.privacy_policy': 'গোপনীয়তা নীতি',
    'login.tagline': 'ঈমান। জীবনধারা। সম্প্রদায়।',
    'login.choose_profile': 'আপনার প্রোফাইল নির্বাচন করুন',
    'login.select_account_type': 'আপনি যে ধরনের অ্যাকাউন্ট তৈরি করতে চান তা নির্বাচন করুন',
    'login.normal_user': 'সাধারণ ব্যবহারকারী',
    'login.normal_user_desc': 'পণ্য ও ট্যুর ব্রাউজ ও ক্রয় করুন',
    'login.seller': 'বিক্রেতা',
    'login.seller_desc': 'আপনার পণ্য তালিকাভুক্ত করুন এবং বিক্রি করুন',
    'login.travel_partner': 'ট্রাভেল পার্টনার',
    'login.travel_partner_desc': 'ব্যবহারকারীদের ট্যুর প্যাকেজ অফার করুন',
    'login.already_have_account': 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে?',
    'login.sign_in': 'সাইন ইন',
    'login.sign_up': 'সাইন আপ',
    'login.welcome_back': 'স্বাগতম',
    'login.enter_credentials': 'সাইন ইন করতে আপনার তথ্য লিখুন',
    'login.create_your_account': 'আপনার অ্যাকাউন্ট তৈরি করুন',
    'login.sign_up_as': 'হিসাবে সাইন আপ করুন',
    'login.full_name': 'পূর্ণ নাম',
    'login.password': 'পাসওয়ার্ড',
    'login.create_account_btn': 'অ্যাকাউন্ট তৈরি করুন',
    'login.back': 'পেছনে',
    'login.dont_have_account': 'অ্যাকাউন্ট নেই?',
    'login.please_wait': 'অপেক্ষা করুন...',
    
    // Home page
    'home.greeting': 'আসসালামু আলাইকুম',
    'home.title': 'বারাকাহ হোম',
    'home.getting_location': 'অবস্থান পাওয়া যাচ্ছে...',
    'home.tap_retry': 'আবার চেষ্টা করতে ট্যাপ করুন',
    'home.current_time': 'বর্তমান সময়',
    'home.next_prayer': 'পরবর্তী নামাজ',
    'home.next_prayer_at': 'পরবর্তী নামাজ',
    
    // Prayer names
    'prayer.fajr': 'ফজর',
    'prayer.dhuhr': 'যোহর',
    'prayer.asr': 'আসর',
    'prayer.maghrib': 'মাগরিব',
    'prayer.isha': 'এশা',
    'prayer.upcoming': 'আসন্ন',
    'prayer.time': 'সময়',
    'prayer.next': 'পরবর্তী',
    
    // Quick actions
    'action.qibla': 'কিবলা',
    'action.quran': 'কুরআন',
    'action.mood': 'দোয়া',
    'action.makkah_live': 'মক্কা লাইভ',
    'action.prayer': 'নামাজ',
    'action.zakat': 'যাকাত',
    'action.scanner': 'স্ক্যানার',
    'action.travel': 'ভ্রমণ',
    
    // Bottom Navigation
    'nav.home': 'হোম',
    'nav.store': 'দোকান',
    'nav.guftagu': 'Guftagu',
    'nav.places': 'স্থান',
    'nav.account': 'অ্যাকাউন্ট',
    'nav.prayer': 'নামাজ',
    'nav.scanner': 'স্ক্যানার',
    
    
    // News page
    'news.title': 'ইসলামিক সংবাদ',
    'news.subtitle': 'সর্বশেষ আপডেটের সাথে অবগত থাকুন',
    'news.load_more': 'আরো লোড করুন',
    'news.category.all': 'সব',
    'news.category.world': 'বিশ্ব',
    'news.category.education': 'শিক্ষা',
    'news.category.community': 'সম্প্রদায়',
    'news.category.charity': 'দাতব্য',
    'news.category.business': 'ব্যবসা',
    
    // Mood page
    'mood.title': 'আপনি কেমন আছেন?',
    'mood.subtitle': 'নির্দেশনার জন্য আপনার মেজাজ নির্বাচন করুন',
    'mood.how_feeling': 'আজ আপনি কেমন অনুভব করছেন?',
    'mood.very_low': 'খুব কম',
    'mood.low': 'কম',
    'mood.neutral': 'স্বাভাবিক',
    'mood.good': 'ভালো',
    'mood.excellent': 'দারুণ',
    'mood.scale_low': 'কম',
    'mood.scale_high': 'বেশি',
    'mood.try_again': 'পেছনে',
    'mood.new_quote': 'নতুন উক্তি',
    
    // Menu
    'menu.home': 'হোম',
    'menu.prayer_times': 'নামাজের সময়',
    'menu.qibla': 'কিবলা',
    'menu.quran': 'কুরআন',
    'menu.makkah_live': 'মক্কা লাইভ',
    'menu.zakat': 'যাকাত ক্যালকুলেটর',
    'menu.shop': 'দোকান',
    'menu.progress': 'অগ্রগতি',
    'menu.account': 'অ্যাকাউন্ট',
    'menu.sign_out': 'সাইন আউট',
    
    // Language selector
    'language.select': 'ভাষা নির্বাচন করুন',
    'language.english': 'ইংরেজি',
    'language.urdu': 'উর্দু',
    'language.arabic': 'আরবি',
    'language.turkish': 'তুর্কি',
    'language.indonesian': 'ইন্দোনেশীয়',
    'language.malay': 'মালয়',
    'language.tamil': 'তামিল',
    'language.bengali': 'বাংলা',
    'languageSelector.title': 'ভাষা',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('barakah-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('barakah-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  // RTL languages: Arabic, Urdu
  const direction = (language === 'ar' || language === 'ur') ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.dir = direction;
    document.documentElement.lang = language;
  }, [language, direction]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, direction }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    // Provide a fallback for HMR or edge cases where provider isn't ready
    return {
      language: 'en' as Language,
      setLanguage: () => {},
      t: (key: string) => translations.en[key] || key,
      direction: 'ltr' as const,
    };
  }
  return context;
};
